name = "InHouseFNM"
uuid = "325a905e-d147-45ac-9d6c-064569d20dc1"
authors = ["Invenia Technical Computing Corporation"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"

[compat]
ElectricityMarkets = "1.14"
FullNetworkDataPrep = "0.2"
GLPK = "0.14"
JuMP = "0.21"
PowerSystems = "0.28"
julia = "1"

[extras]
ElectricityMarkets = "fc2b1cf9-69e4-584d-aa69-fb07a6454787"
FullNetworkDataPrep = "a21943b2-60f3-11e9-2dbc-73f7bf1f23ac"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ElectricityMarkets", "FullNetworkDataPrep", "GLPK", "Test"]
